<?php
    /*Error Hnadling*/
    CONST APP_SUSPENDED             = "APP_SUSPENDED";
    CONST NO_DATA                   = "NO_DATA";
    CONST NO_REGISTERED             = "NO_REGISTERED";
    CONST NO_ACTIVATION             = "NO_ACTIVATION";
    CONST SUCCESS                   = "SUCCESS";
    CONST EMPTY_VALUE               = "EMPTY_VALUE";
    CONST NUMBER_ONLY               = "NUMBER_ONLY";
    CONST STRING_ONLY               = "STRING_ONLY";
    CONST FAILED                    = 'FAILED';
    CONST ACTIVATION_CODE_EXPIRED   = "ACTIVATION_CODE_EXPIRED";
    
    /*Log*/
    CONST USER_REGISTER               = 'USER_REGISTER';
    CONST USER_ACTIVATION             = 'USER_ACTIVATION';
    CONST USER_INSERT_DATA_PASIEN     = 'USER_INSERT_DATA_PASIEN';
    CONST USER_UPDATE_DATA_PASIEN     = 'USER_UPDATE_DATA_PASIEN';
    CONST USER_LOGIN                  = 'USER_LOGIN';
    CONST USER_UPDATE_AKUN            = 'USER_UPDATE_AKUN';
    CONST USER_REACTIVATION           = 'USER_REACTIVATION';
    CONST USER_OPEN_FASKES            = 'USER_OPEN_FASKES';
    CONST USER_OPEN_KLINIK            = 'USER_OPEN_KLINIK';
    CONST USER_OPEN_RIWAYAT_PROGRESS  = 'USER_OPEN_RIWAYAT_PROGRESS';
    CONST USER_OPEN_RIWAYAT_SELESAI   = 'USER_OPEN_RIWAYAT_SELESAI';
    CONST USER_ANTRI                  = 'USER_ANTRI';
    CONST USER_OPEN_LIST_BLOG         = 'USER_OPEN_LIST_BLOG';
    CONST USER_OPEN_BLOG              = 'USER_OPEN_BLOG';
    CONST USER_COMMENT                = 'USER_COMMENT';
    CONST USER_EDIT_COMMENT           = 'USER_EDIT_COMMENT';
    CONST USER_DELETE_COMMENT         = 'USER_DELETE_COMMENT';
    CONST USER_DELETE_BLOG            = 'USER_DELETE_BLOG';
    CONST USER_EDIT_BLOG              = 'USER_EDIT_BLOG';
    CONST USER_INSERT_BLOG            = 'USER_INSERT_BLOG';
?>